artifacts_root: artifacts

data_ingestion:  
root_dir: artifacts/data_ingestion
source_url: https://github.com/MEGHANASEEPANA/datasets/raw/refs/heads/main/winequality-red.zip
local_data_file: artifacts/data_ingestion/data.zip
unzip_dir: artifacts/data_ingestion